pub/assets/js/hound.js

You're already using `history.pushState()` to track each search. This listens for `popstate` to enable going back through your history of searches.

Add back-button support

---

README.md

Fix word repetition typo in README

---

pub/assets/js/hound.js

Fixes #45 by simply answering the empty query in the frontend with

---

pub/assets/css/hound.css
pub/assets/js/hound.js

Just a slight change to the divider style.

---

pub/assets/js/hound.js
src/hound/config/config.go

See https://github.com/etsy/Hound/issues/75

Add patterns to config object for configurable URLs

---

.gitignore
pub/assets/js/common.js
pub/assets/js/excluded_files.js
pub/assets/js/hound.js
src/hound/cmds/houndd/main.go
src/hound/config/config.go

Fixes some issues in the url patterns PR.
1. Changes mini-templating to use {name} instead of ${name}.
2. Merges url-pattern into a single json property.
3. Makes excluded files page respect url pattern.
4. Introduces common.js file to share between pages.

Url patterns

---

src/hound/vcs/svn.go

Added SVN driver to available drivers - some of the function names don't quite match with the command being run.
Credentials are loaded from `SVN_USERNAME` and `SVN_PASSWORD` environment variables.

Added basic SVN driver

---

ui/assets/js/hound.js

When the files element receives focus just expand the advanced panel.

Fixes #91.

---

config/config.go
searcher/searcher.go

Implements comments on 23e8dbf6b1457ca78e6dad2f1ee2b0b8a9794065.

Small changes to push update coalescing, config defaults

---

.gitignore
README.md
cmds/houndd/main.go
config-example.json
config/config.go
searcher/searcher.go

Adding entries to .gitignore to aid in Mac development
[DEVTOOLS-91] Adding connection limiter
[DEVTOOLS-91] Updating README and config-example.json

[DEVTOOLS-91] Adding connection limiter

---

README.md
cmds/houndd/main.go
config-example.json
config/config.go
searcher/searcher.go

The good news is this passes the 1,000 repo test I created to test out #113.

Add rate limiter to indexing.

---

.gitignore
README.md
ansi/tty.go
ansi/tty_windows.go
codesearch/index/mmap_bsd.go
codesearch/index/mmap_linux.go
codesearch/index/mmap_windows.go
codesearch/index/read.go
codesearch/index/write.go
index/index.go

Makes hound build and run on windows. I noticed there was an existing PR from February where there was no more progress being made so I'm suggesting the changes I made to make it work on Windows.

Fixes for hound on windows

---

ui/assets/index.tpl.html
ui/assets/open_search.tpl.xml
ui/bindata.go
ui/content.go
ui/ui.go

See http://www.opensearch.org/Home for details on Open Search.

Adding open search description to enable search from the URL bar

---

ui/assets/js/hound.js

Use ignore case setting while highlighting results

---

Dockerfile

Revert "Dockerfile: Run houndd as unprivileged user"

---

vcs/git.go

Use more robust git combination that is tolerant to force pushed
branches.

Fixes #183.

---

README.md

clarify readme as suggested in issue #134 .

clarify that file:// only works on local folders that are repositories

---

codesearch/index/write.go
codesearch/index/write_test.go

Fixes a codesearch bug in the index writer.

---

config-example.json

Adding the config for the health-check path to the example config.

Added health-check-uri to example config.

---

config-example.json
config/config.go
ui/assets/index.tpl.html
ui/bindata.go
ui/ui.go

`ui/bindata.go` seems to be out of date in #336

Rebuild ui/bindata.go for #336

---

Dockerfile

This fixing the docker build issue.

Dockerfile should use github.com/hound-search

---

api/api.go

This patch adds support for github webhooks. This means that committing to a repository sends a webhook request to hound, which then re-indexes the repository. We've been using this in production for about 2 years on our Github Enterprise with 1000+ repos. Without this patch it was basically not possible as we had to re-index that many repos all the time. As per a previous issue I tried creating tests, but my go skills weren't enough. I couldn't get it to work, mainly because I think it means a bit of a rewrite of api.go.  
I'm sending this PR so someone can decide if it's useful at all, and if not, just close the PR. Since our company will shutter in a few months as least the code is out there.

support github webhook

---

.github/workflows/go.yaml
client/client.go
cmds/houndd/main.go
codesearch/index/merge.go
codesearch/index/regexp.go
codesearch/regexp/copy.go
index/index.go

This PR fixes the linting check by updating a handful of dependencies.
It also runs builds for the two supported versions of Go, and drops all but v1.14 from the existing checks.
This is an investigation into https://github.com/hound-search/hound/issues/419

Fix the linter, update golang versions.

---

.github/workflows/go.yaml

Adding that PRs kick off pull requests

kick off for pull requests

---

README.md

Update list of maintainers with additional volunteers

---

cmds/houndd/main.go

**What kind of change does this PR introduce?**

Bump the version
