hound-search/hound

- src/hound/cmds/houndd/main.go
When running houndd the output status line doesn't handle --addr with a hostname included.
I've never written any go before, so this might be complete nonsense :)
**Before**
./bin/houndd
All indexes built, running server at http://localhost:6080...
./bin/houndd --addr 127.0.0.1:6800
All indexes built, running server at http://localhost127.0.0.1:6800...
**AFTER**
./bin/houndd
All indexes built, running server at http://localhost:6080...
./bin/houndd --addr 127.0.0.1:6800
All indexes built, running server at http://127.0.0.1:6800...
> Fix houndd server location output line

- src/hound/config/config.go
- src/hound/searcher/searcher.go
- src/hound/vcs/git.go
- src/hound/vcs/hg.go
- src/hound/vcs/vcs.go
This was actually fairly painless. I refactored all repo accesses to use a new `hound/vcs` package (it replaces `hound/git`) which works similar to `database/sql` in that you can register plugins to handle operations.
The only odd thing is that in stead of doing `hg id -i`, I used `hg log -r tip --template '{node}'` which should give a 40 character sha, not the shorter one, as there's a regex used in existing that's somewhat lazy in looking at directory names.
Also, most of the hg plugin was a direct copy from the git plugin with a few renames. It might be worthwhile to clean it up a bit.
The config adds a new vcs option which allows you to specify the vcs of a repository. It defaults to git.
Docs have not been updated to say that mercurial is supported yet, as I'd like to get some …
> Refactor internal VCS api and add Mercurial support

- src/hound/vcs/hg.go
* Pull was just pulling in the code. `-u` will make pull also update the checked out repo to the latest revision.
* For revisions `tip` is simply the highest numbered revision, while `.` is the currently checked out revision.
> Small fixes for Mercurial Pull and HeadHash

- pub/assets/css/hound.css
- pub/assets/js/hound.js
Try to search "git" in this repo. There are more matches in README.md and I find it useful to visually separate grouped lines by margin and border.
> Visually separate matches in one file

- pub/assets/css/hound.css
- pub/assets/js/hound.js
The ```matches``` div had purpose, sorry :-)
> Allow borders in .match div grow to the end of line

- pub/assets/css/hound.css
- pub/assets/js/hound.js
Provide a more visible way to hide the advanced menu.
> Add an element for user to hide advanced menu

- src/hound/api/api.go
The correct header string is 'Access-Control-Allow-Origin'.
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
> Set correct CORS header in API endpoint.

- pub/assets/js/hound.js
This is a slightly more flexible solution for #19 than
d2c1d98deb169f2539668d6992207a9e9d83b8dd, which worked for private
github.com repos but not for repos on a different domain.
> fix 404s for Github Enterprise repos (see #19)

- pub/assets/js/common.js
- pub/assets/js/excluded_files.js
- pub/assets/js/hound.js
- src/hound/index/index.go
- src/hound/searcher/searcher.go
Bitbucket style URLs differ from github style URLs in two ways:
1) Bitbucket SSH repository URLs takes the form of:
`ssh://hg@bitbucket.org/username/Foo` (vs
`git@github.com:username/Foo.git`)
2) Direct links to source file lines require the commit hash/revision
id, following this pattern: `{url}/src/{rev}/{path}{anchor}`.
This patch addresses both these concerns to allow for direct file
linking to bitbucket.
This required a change to bubble up the revision to the UI layer, which
can be then fed in to the `UrlToRepo` function for final formatting via
a custom `url-pattern` (as defined above).
Server side, the `revision` value is bound to each `index` upon
opening. The `index.Search` function returns this value in the
`SearchResults` struct.
> Support linking to bitbucket style URLs

- Makefile
The `clean` target in the Makefile was missing the `r` flag.
> Makefile - fixed `rm` cmd in the  `clean` target

- .gitignore
- Makefile
This solves a very practical problem with running the tests now. I want to be able to run all tests in the repository using `go get github.com/etsy/hound/...` but currently this tries to pick up the package that are in the `build` directory. Making this a dot directory hides it from the the recursive test discovery.
> Use .build instead of build so that go test works properly.

- Dockerfile
- README.md
If we use an ONBUILD instruction this container can be automatically build via docker.io
example https://registry.hub.docker.com/u/sstarcher/hound/
Once that is happening instead of cloning this repo and adding a config.json locally you could do the following.
Dockerfile
```
From sstarcher/hound
```
config.json
```
{ ....}
```
Whatever your config is
Those 2 files would be enough to run hound.
> Use onbuild

- ui/assets/index.tpl.html
I am seeing a blank page in IE10. Adding the "X-UA-Compatible" tag to the html fixes the issue.
> Fix blank page in Internet Explorer

- ui/assets/css/hound.css
Ensure that we show the pointer cursor on the advanced search pane when
closed, but only on the chevron when the pane is open.
Closes #184.
> Only show pointer cursor on the chevron.

- Dockerfile
Being root in a container is like being root on the host machine[1]. Houndd
doesn't need root priviliges so it can be run as unprivileged user.
[1] https://stackoverflow.com/questions/19054029/security-of-docker-as-it-runs-as-root-user
> Dockerfile: Run houndd as unprivileged user

- cmds/houndd/main.go
- searcher/searcher.go
Addresses #168. This provides a way to explicitly shut down a searcher instead of stealing limiter tokens as suggested in the ticket. This may be useful for implementing config reloads or allowing searchers to perform cleanup work before shutting down.
> Add graceful shutdown on SIGTERM

- Dockerfile
While running Hound:
```
Cloning into 'vcs-2db7dbdc56d69442a4c1efbe143ef24504efc4a1'...
error: cannot run ssh: No such file or directory
```
To isolate, I shelled into the container and found that ssh was missing:
```
$ docker run -it --rm -p 80:6080 --entrypoint=/bin/sh --name houndd -v $(pwd):/hound etsy/hound -s
/ # ssh
/bin/sh: ssh: not found
```
> openssh seams to be missing

- Dockerfile
- README.md
- default-config.json
We are currently misusing `ONBUILD` in our Dockerfile. The downside of that was that you couldn't even run the hound image without first creating a little config.json file. This update uses a `VOLUME` that already contains a minimal config.json (that indexes this repository) and it's trivial to use a volume on the command line to mount your custom config.
> Simplify Dockerfile

- index/index_test.go
Fatal doesn't allow use of formatting directive like %s. Instead, Fatalf
should be used when we need formatting directives.
Fixes - https://travis-ci.org/etsy/hound/jobs/305180308#L493
@stanistan this should be merged first of all so that other pull requests can be rebased on top of this commit to get a fair run of tests on travis.
> index: fix warning coming from use of %s in Fatal

- .travis.yml
Add golang versions 1.6, 1.7, 1.8 and 1.9 to automated tests.
> travis: add more recent go versions until 1.9

- ui/content.go
- ui/ui.go
This turned out to be more cumbersome than I had expected it to be. Below
is the description of what I did and the rationale behind it.
open_search.xml file was being served using html/template package and
since it doesn't know about xml contexts, it changes the first character
of xml template "<" into "\&lt;".
Now, we use two different packages:
- html/template - for parsing html template files
- text/template - for parsing text or xml template files
Here it's arguable that we could use encoding/xml package to parse the
xml template files in a better way. However, to keep the parsing logic
consistent, we are fine with using text/template only. If, in future, we
come across a use case where we want to parse and serve xml file where
we need to know the xml context while parsing the …
> Fix xml parsing of open_search.xml

- searcher/searcher.go
This patch attempts to improve the startup time of hound vastly in cases
when we have huge number of repositories and hound would generally take
long time to start because of its sequential nature of indexing.
Now, we have the startup indexing in a concurrent way while respecting
the config.MaxConcurrentIndexers parameter set by users in config.json.
Fixes https://github.com/etsy/hound/issues/250
> searcher: make indexing of repos concurrent

- cmds/houndd/main.go
- package-lock.json
- package.json
- ui/ui.go
The current `houndd --dev` setup for assets is broken because it loads sourcecode directly and chokes on the recently added ES6 import statement.
This change spawns [webpack-dev-server](https://github.com/webpack/webpack-dev-server) when running `houndd --dev` and points the `<script>` tags at that host for the built assets. 
It appears that the webpack server is fully cleaned up when the process exits, I wasn't sure if I was supposed to do something in the shutdown function ʅʕ•ᴥ•ʔʃ
> Adds webpack-dev-server to houndd --dev

- cmds/houndd/main.go
- config/config.go
- ui/bindata.go
- web/web.go
It is really difficult to run Hound in kubernetes right now because the time it takes to build all the indexes and start serving HTTP traffic can vary widely. The readiness probe has to be constantly adjusted as you change your configuration. This change brings up the HTTP server before the searchers are made. But while the initial indexes are building, only the health check will return a 200 response, all other routes will return 503. Once the indexes are ready, all routes will be enabled.
> Add the ability to respond to health checks prior to indexes being built.

- searcher/searcher.go
On re-restarting hound after the initial indexing, I got this:
```
fatal error: concurrent map writes
goroutine 49 [running]:
runtime.throw(0x14ae4f5, 0x15)
/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:774 +0x72 fp=0xc0001bbd78 sp=0xc0001bbd48 pc=0x102fb32
runtime.mapassign_fast64ptr(0x141cd80, 0xc000464060, 0xc000268e60, 0xc0004ee7e0)
/usr/local/Cellar/go/1.13.4/libexec/src/runtime/map_fast64.go:191 +0x369 fp=0xc0001bbdb8 sp=0xc0001bbd78 pc=0x1013829
github.com/hound-search/hound/searcher.(*foundRefs).claim(...)
/Users/igor/go/src/github.com/hound-search/hound/searcher/searcher.go:88
github.com/hound-search/hound/searcher.newSearcher(0xc000190580, 0x16, 0xc000168600, 0x22, 0xc00016a0a0, 0xc00044ee60, 0xc0004022a0, 0x657461677261662f, 0x20200a227469672e, 0x2020200a2c7d2020) …
```
> fix race condition in foundRefs.claim()

- config-example.json
This avoids a redirect when opening bitbucket links. It should redirect browser-side after the first load since they are using HSTS, but I still see a flash for some reason. Some browsers might not support HSTS, so might as well avoid the issue entirely?
> Add https to bitbucket base-url

- README.md
- cmds/houndd/main.go
The ellipsis in the listen URL is making the listen URL non-clickable. This is just a small change, but it improves quality of life for local toying quite a bit.
> make listen URL clickable in iTerm

- .gitignore
- config-example.json
- config/config.go
- config/config_test.go
- vcs/git.go
- vcs/git_test.go
Currently, only the default ref (`master`) is supported.
- Allow target non-default target refs to be specified via configs.
- Add config-driven target ref auto-detection using the `HEAD` branch.
- Update default repo base URL pattern to link to the content revision,
accounting for potential non-default target ref usage.
- Add global-level VCS configs which are merged into the repo-level configs
during startup (repo-level vals take precedence).
> Git VCS driver: Support non-default target refs

- api/api.go
- index/index.go
- ui/assets/css/hound.css
- ui/assets/js/hound.js
This PR adds a search field to exclude file paths with a regexp. It works exactly like the current file path search, except if it matches it rejects the file.
This is the same as #223 but because I had removed my hound fork a long time ago I'm unable to update that PR.
I rebased on the latest master and did a quick test that it still works.
> Exclude file path

- README.md
I don't think there's a clear way to see who has push privs to this repo from the public, and even if there is, the "Get In Touch" section should probably list the maintainers.
> Update README with contact info for maintainers.

- README.md
This PR adds a bit more detail to the quick start instructions, which should provide people new to Go's tooling and customs with the information they need to run `houndd` locally just by reading the quick start instructions.
> add detail around $GOPATH in README's quick start instructions

- Dockerfile
If you run the `docker build . -t nice/hound`, you will see the following information
```bash
OK: 12750 distinct packages available
bzr (missing):
ERROR: unsatisfiable constraints:
required by: world[bzr]
The command '/bin/sh -c apk update 	&& apk add go git subversion libc-dev mercurial bzr openssh 	&& go install github.com/hound-search/hound/cmds/houndd 	&& apk del go 	&& rm -f /var/cache/apk/* 	&& rm -rf /go/src /go/pkg' returned a non-zero code: 1
```
This is because `bzr` has become unmaintained due to its Python2 upstream: https://gitlab.alpinelinux.org/alpine/aports/-/tree/3.12-stable/unmaintained%2Fbzr
This PR pins the Alpine's version to 3.11.6 to avoid this issue. The latest is 3.12.
A minor improvement: 
I also removed the redundant COPY because it won't be used at all. When …
> Pin Alpine version to 3.11.6

- README.md
- docs/config-options.md
[issue-#367](https://github.com/hound-search/hound/issues/367)
Add documentation for all the config options
> Added new folder docs with config-options description on options.

- Dockerfile
This fixes the Dockerfile such that building the container image is possible using something like:
docker build .
Without adding the `semver` package, that build command would fail with the message
```
go/src/github.com/hound-search/hound/cmds/houndd/main.go:17:2: cannot find package "github.com/blang/semver" in any of:
/usr/lib/go/src/github.com/blang/semver (from $GOROOT)
/go/src/github.com/blang/semver (from $GOPATH)
The command '/bin/sh -c apk update 	&& apk add go git subversion libc-dev mercurial bzr openssh 	&& go install github.com/hound-search/hound/cmds/houndd 	&& apk del go 	&& rm -f /var/cache/apk/* && rm -rf /go/src /go/pkg' returned a non-zero code: 1
```
Note that I am not super-knowledgeable about the golang ecosystem. If it is possible to build the image without such …
> Install dependencies in Dockerfile

- README.md
depending on where you put your hound data it could be competing with windows search indexer, which doesnt need to index this stuff. 
Also (for windows) its common for developers to have IDE and repo folders excluded form realtime virus scanning. That also competes with this indexer
> Adding a tip for windows users

- Dockerfile
It appears that hound leaks zombie processes when running within a Docker container as built by the project Dockerfile. Maybe because Hound does not explicitly wait for children or does not handle SIGCHLD and implicitly defers back to system init for child termination handling.
In my environment, hound polls a couple hundred git repositories. The process table starts filling up with defunct/zombie `ssh` processes immediately, until eventually (after approx. 24-48h) the process table is exhausted, preventing any further processes being spawned. When running Docker in default configuration, this actually has impact on the entire host system, as the number of processes per containers is not capped.
Workaround for Docker: Launch the hound container with the `docker run --init` option. That …
> Fix hound zombie process leak when running as container

- README.md
We're planning on renaming the default branch to `main`, and we want to give users a heads up a week in advance.
> Add a warning for the default branch rename

- ui/assets/js/hound.js
Individual links to line numbers open in a new target. Links to the file (at the top of the list of line number links) open in the same window / tab. This PR makes them behave consistently with line links.
Add rel="noopener noreferrer" to _blank links
> Give file links a target of blank

- .github/PULL_REQUEST_TEMPLATE.md
Creating a template for providing more information and checks for each PR.
See #366
> Adding Pull Request Template for providing more information in each PR

- README.md
Currently, the README suggests running an outdated version of hound. There's been a lot of good work done in the past [3 years](https://hub.docker.com/r/etsy/hound/tags).
The container registry was updated in https://github.com/hound-search/hound/pull/401
> Update README to use ghcr.io

- README.md
It's been almost a year since we renamed the default branch to `main`. The warning can probably be taken out.
> Remove default branch warning

- .dockerignore
- .gitignore
This is a very small change. If you follow the README, you will end up creating a `config.json` in the root of the repo. This will prevent that from causing a non-clean git status.
It is also helpful for development so that you can have a config file in the repo for testing.
This PR also adds a .dockerignore file which mirrors .gitignore with a few exceptions. Without it, building locally sucks if you have large test db test data in your repo as Docker copies all of that into the context to build even though it's not needed.
> Add config.json to .gitignore and add .dockerignore

- .github/workflows/go.yaml
- Dockerfile
-- CI change to enable multi platform docker builds
When following the `Using Docker` section of README on arm laptop I get a docker warning about the image platform mismatch.
My goal with this change is to have GH Actions build both amd64 and arm64 platformed images
> Adding the setup-qemu-action to enable multiplatform docker builds from github actions

- Makefile
- README.md
- tools/tools.go
Since Hound is now a proper Go module, we can avoid a lot of the complexity of setting up the `GOPATH` that we used to have to deal with. This updates the `Makefile` so that `GOPATH` hijinks is no longer required to build locally. The one caveat is that `houndd` and `hound` will be built into `.build/bin` instead of `$GOPATH/bin`. 
A few other changes explained:
A go module should explicitly reference its dependencies somewhere. `go mod tidy` is often used to cull dependencies that are no longer needed in a go module. This poses a problem for dependencies that are build related as they are only referenced in the build system. A convention that is often used, and which I'm using here, is to add an explicit code reference to those …
> Update Makefile to reflect the move to a go module.

- README.md
With the help from [this issue](https://github.com/hound-search/hound/issues/423), this PR add a manual installation option as well as specifying directory for `config.json` in README
All the above don't apply to this PR
> chore: add manual install option

- CONTRIBUTING.md
- client/client.go
- config-example.json
- config/config.go
- docs/config-options.md
- ui/assets/js/hound.js
This PR introduces an optional `display-name` field in the repo configuration, which allows the user to override the default `parent/repo` format.  This is useful, for example, when indexing the same repo with different config options (e.g. main branch and feature branch).
E.g. this config file:
```
{
"dbpath" : "db",
"vcs-config" : {
"git": {
"ref" : "main"
}
},
"repos" : {
"Hound" : {
"url" : "https://github.com/awf/hound.git"
},
"Hound/alpine" : {
"url" : "https://github.com/hound-search/hound.git",
"display-name" : "Hound (alpine)",
"vcs-config" : {
"git": {
"ref" : "alpine"
}
}
}
}
}
```
produces this output (the red text) from the CLI client
and this on HTML
If adding a **new …
> Add `display-name` option to customize/disambiguate output

- api/api.go
- api/api_test.go
- cmds/houndd/main.go
- config/config.go
- index/dummy_en.txt
- index/dummy_es.txt
- index/index.go
- index/index_test.go
- web/web.go
These changes were copied from https://github.com/hound-search/hound/pull/408 which was closed cause I accidentally pushed the main branch on the contributor's fork(I meant to push a copy of his branch with my changes instead of main).
I didn't make any other changes besides adding some [tests](https://github.com/hound-search/hound/commit/1103c328d5fef9e0776b940cfc28d39fa12b622e) for `parseAsIntValue` and `parseAsUintValue`.
> Add support for manually setting a limit on results(copy)

- ui/assets/css/hound.css
When I want to copy multiple lines of code from the search results, the line numbers are also copied.
So when I paste this into IDE or console, it may cause syntax errors.
The solution is to prevent line numbers from being copied in search results using CSS.
I hope this little trick is helpful.
P.S. As I noticed, now there is no need to regenerate`ui/bindata.go`. So this line may be deleted from PR template. Right?
> Prevent line numbers from being copied in search results
